# -*- coding: utf-8 -*-
"""Suda Installation_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BxuwXdds1MkIl7QtvvyIn3lGUyaMqoxX
"""

!pip install suda

!pip install pandas --no-build-isolation

!apt-get install libatlas-base-dev gfortran

!pip install pandas

!python --version

!pip install --upgrade pip setuptools wheel

!pip install pandas

!pip install --upgrade pip setuptools wheel

!pip install suda

!pip install suda==0.2.0

!conda install pandas

!apt-get update
!apt-get install <required-dependency>

!pip install git+https://github.com/98Fabiha/suda_package_repository.git

!python -m venv myenv
!source myenv/bin/activate
!pip install suda

!pip install pandas==1.1.5

!apt-get install libatlas-base-dev gfortran

!pip install suda

!pip install --upgrade pip setuptools wheel

!pip install suda

!pip install pandas --only-binary :all:

!pip install suda

!pip show pandas

!pip install suda --no-deps

import pandas as pd
from suda.suda2 import suda2

!pip install suda --no-deps --force-reinstall

!pip show suda

from suda import suda2

import suda
print(dir(suda))

!cd /usr/local/lib/python3.10/dist-packages

!ls

import sys
print(sys.path)

!pip show suda

import pandas as pd
from suda import suda

from google.colab import files

uploaded = files.upload()
df = pd.read_csv('Book1research.csv')

categorical_columns = ['ENSG00000000003', 'ENSG00000000005', 'ENSG00000000419','ENSG00000000457','ENSG00000000460','ENSG00000000938','ENSG00000000971','ENSG00000001036','ENSG00000001084']  # Replace with your own column names
df_subset = df[categorical_columns]

data_as_list = df_subset.values.tolist()

results = suda (data_as_list)

column_names = ['ENSG00000000003', 'ENSG00000000005', 'ENSG00000000419','ENSG00000000457','ENSG00000000460','ENSG00000000938','ENSG00000000971','ENSG00000001036','ENSG00000001084']
data_as_df = pd.DataFrame(df, columns=column_names)

results = suda(data_as_df)