# -*- coding: utf-8 -*-
"""trial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17FasyzGvCR0CiFBaAl87TAoXLAfeM6EK
"""

!python --version

!pip install --upgrade pip setuptools wheel

!pip install pandas

!pip show pandas

!pip install suda --no-deps

!pip show suda

import suda
print(dir(suda))

import pandas as pd
from suda import suda

from google.colab import files

uploaded = files.upload()
df = pd.read_csv('united_tf_target_test (1).csv')

categorical_columns = df.columns.tolist()

df_subset = df[categorical_columns]

for col in df_subset.select_dtypes(include=['object']).columns:
    df_subset[col] = pd.Categorical(df_subset[col])
    if 0 not in df_subset[col].cat.categories:
        df_subset[col] = df_subset[col].cat.add_categories([0])

result = suda(df_subset)

import IPython.display
IPython.display.display(IPython.display.HTML("<style>.output_scroll { height: 10000px; }</style>"))  # Adjust 10000px as needed

import sys
original_stdout = sys.stdout  # Store original stdout
with open('output.txt', 'w') as f:
    sys.stdout = f  # Redirect stdout to the file
    # Your code that needs to write to the file should go here
sys.stdout = original_stdout

result.to_csv('result.csv', index=False)
from google.colab import files
files.download('result.csv')

for col in df_subset.select_dtypes(include=['object']).columns:
    df_subset[col] = pd.Categorical(df_subset[col])
    if 0 not in df_subset[col].cat.categories:
        df_subset[col] = df_subset[col].cat.add_categories([0])

result = suda(df_subset)

result.to_csv('result.csv', index=False)
from google.colab import files
files.download('result.csv')

print(result)